### ISSUE TITLE
 gcloud:run  error

### ISSUE THREAD

**Issue by gitsgx** [GoogleCloudPlatform/gcloud-maven-plugin#109]
After successful running of "mvn clean install", 
Run:  ../apache-maven-3.3.9/bin/mvn gcloud:run 

[INFO] Creating staging directory in: /.../target/appengine-staging
[ERROR] 
java.util.NoSuchElementException
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
	at com.google.common.collect.Iterators.find(Iterators.java:737)
	at com.google.common.collect.Iterables.find(Iterables.java:642)
	at com.google.appengine.SdkResolver.getSdk(SdkResolver.java:50)
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.resolveAndSetSdkRoot(AbstractGcloudMojo.java:619)
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.executeAppCfgStagingCommand(AbstractGcloudMojo.java:663)
	at com.google.appengine.gcloudapp.GCloudAppRun.getCommand(GCloudAppRun.java:325)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:279)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by loosebazooka** [comment]
Is there a reason you haven't switched to https://github.com/GoogleCloudPlatform/app-maven-plugin ? Perhaps we could help with the transition.
