### ISSUE TITLE
Cannot deploy to app engine any more.

### ISSUE THREAD

**Issue by chriszohno** [GoogleCloudPlatform/gcloud-maven-plugin#110]
From last week I cannot deploy my app any more. I am not sure what changed.
I am getting this error now. Do you have any idea why?

ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:deploy (default-cli) on project gaeapp: Execution default-cli of goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:deploy failed. NoSuchElementException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:deploy (default-cli) on project gaeapp: Execution default-cli of goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:deploy failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:deploy failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.util.NoSuchElementException
        at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
        at com.google.common.collect.Iterators.find(Iterators.java:737)
        at com.google.common.collect.Iterables.find(Iterables.java:642)
        at com.google.appengine.SdkResolver.getSdk(SdkResolver.java:50)
        at com.google.appengine.gcloudapp.AbstractGcloudMojo.resolveAndSetSdkRoot(AbstractGcloudMojo.java:619)
        at com.google.appengine.gcloudapp.AbstractGcloudMojo.executeAppCfgStagingCommand(AbstractGcloudMojo.java:663)
        at com.google.appengine.gcloudapp.GCloudAppStage.executeStaging(GCloudAppStage.java:153)
        at com.google.appengine.gcloudapp.GCloudAppDeploy.execute(GCloudAppDeploy.java:41)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

**Comment by loosebazooka** [comment]
Is there a reason you haven't switched to https://github.com/GoogleCloudPlatform/app-maven-plugin ? Perhaps we could help with the transition.

**Comment by chriszohno** [comment]
I used app-maven-plugin at first.  Then I followed Google's documentation and switched to gcloud tool. After switching everything worked until last week.
So it is better to use app-maven-plugin?

**Comment by chriszohno** [comment]
Tried app-maven-plugin, it works.
Does it use appengine-web.xml file? It seems the version from appengine-web-app is not used.

**Comment by loosebazooka** [comment]
Which document are you referring to?, I will contact someone to update the documentation. If you wish to use a plugin that uses gcloud, it is better to use https://github.com/GoogleCloudPlatform/app-maven-plugin

```
<dependency>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <version>1.3.1</version>
</dependency>
```

Yes it still uses appengine-web.xml file.

**Comment by loosebazooka** [comment]
Correct, `<version>`/`<application>` must be configured in the pom.xml now, in the plugin configuration.

```
<deploy.project>
<deploy.version>
```
