### ISSUE TITLE
Utils  getCloudSDKLocation() assumes sdk is installed in home directory

### ISSUE THREAD

**Issue by itsjimbo** [GoogleCloudPlatform/gcloud-maven-plugin#24]
Potential problem with Utils, getCloudSDKLocation() assumes that the google-cloud-sdk in in user.home, and there is no -D switch to override

```
gcloudDir = System.getProperty("user.home") + "/google-cloud-sdk";
```

```
[ERROR] 
org.apache.maven.plugin.MojoExecutionException: Unkown Google Cloud SDK location.
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.setupInitialCommands(AbstractGcloudMojo.java:160)
	at com.google.appengine.gcloudapp.GCloudAppRun.getCommand(GCloudAppRun.java:306)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:292)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
```

### Quick Solution (hack)
Symbolic link the directory.. in my case I installed  google-cloud-sdk  under /opt
```
j~$ mkdir -p /usr/local/share/google/
j:~$ ln -s /opt/google-cloud-sdk /usr/local/share/google/google-cloud-sdk
```

**Comment by ludoch** [comment]
The code is like:
    if (gcloud_directory == null) {
      gcloud_directory = Utils.getCloudSDKLocation();
    }
So you can specify your own sdk location via the the gcloud_directory
config.

Doc contains: (
https://cloud.google.com/appengine/docs/java/managed-vms/maven)

# To specify a non default Cloud SDK installation directory:
  $ mvn gcloud:run -Dgcloud.gcloud_directory=YOUR_OWN_SPECIFIC_INSTALLATION_PATH

**Comment by itsjimbo** [comment]
Thanks, missed that param (RTFM!!) sorry bout that
