### ISSUE TITLE
gcloud plugin fails if invoked on jdk8

### ISSUE THREAD

**Issue by bfg** [GoogleCloudPlatform/gcloud-maven-plugin#54]
I've just tried maven gcloud plugin with java7 appengine app (build is done using 1.7 target); It fails with the following exception if invoked using  oracle 8u60 jdk:

```
[INFO] Oct 16, 2015 6:28:51 AM com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction apply
[INFO] SEVERE: Failed to start server
[INFO] java.lang.RuntimeException: Unable to restore the previous TimeZone
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.restoreLocalTimeZone(DevAppServer2Impl.java:341)
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:244)
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:56)
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:208)
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:206)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:206)
[INFO]  at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:128)
[INFO]  at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
[INFO]  at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:48)
[INFO]  at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
[INFO]  at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)
[INFO] Caused by: java.lang.NoSuchMethodException: java.util.TimeZone.setDefaultInAppContext(java.util.TimeZone)
[INFO]  at java.lang.Class.getDeclaredMethod(Class.java:2130)
[INFO]  at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.restoreLocalTimeZone(DevAppServer2Impl.java:337)
[INFO]  ... 11 more
```

**Comment by GabiAxel** [comment]
The following configuration solved it for me:
```xml
<configuration>
  <jvm_flag>
    <jvm_flag>-Dappengine.user.timezone=UTC</jvm_flag>
  </jvm_flag>
</configuration>
```

**Comment by chanseokoh** [comment]
Is this fixed in recent gcloud releases by any chance?
