### ISSUE TITLE
Error while running mvn gcloud:deploy

### ISSUE THREAD

**Issue by coldistric** [GoogleCloudPlatform/gcloud-maven-plugin#60]
**What steps will reproduce the problem?**
I'm following the tutorial created  by google in order to understand the use of manged VMs using java.

Here is the link: https://github.com/GoogleCloudPlatform/appengine-java-vm-guestbook-extras

At stage 1 I'm trying to deploy a sample guestBook app which use  java  libraries that don't run on App Engine. When I use the command mvn gcloud:deploy it told me that the build end with failure and that there is an import error which is : No module named googlecloudsdk.core.util.

**What is the expected output? What do you see instead?**
I expected the application to be deployed on manged VMs successfully.

Instead I'm seeing this

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building guestbook-stage1 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> gcloud-maven-plugin:2.0.9.81.v20151008:deploy (default-cli) > package @ guestbook-stage1 >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ guestbook-stage1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Owner\Documents\code\git\google\stage1\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ guestbook-stage1 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ guestbook-stage1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Owner\Documents\code\git\google\stage1\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ guestbook-stage1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ guestbook-stage1 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ guestbook-stage1 ---
[INFO] Packaging webapp
[INFO] Assembling webapp [guestbook-stage1] in [C:\Users\Owner\Documents\code\git\google\stage1\target\guestbook-stage1-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Users\Owner\Documents\code\git\google\stage1\src\main\webapp]
[INFO] Webapp assembled in [145 msecs]
[INFO] Building war: C:\Users\Owner\Documents\code\git\google\stage1\target\guestbook-stage1-1.0-SNAPSHOT.war
[INFO] WEB-INF\web.xml already added, skipping
[INFO] 
[INFO] <<< gcloud-maven-plugin:2.0.9.81.v20151008:deploy (default-cli) < package @ guestbook-stage1 <<<
[INFO] 
[INFO] --- gcloud-maven-plugin:2.0.9.81.v20151008:deploy (default-cli) @ guestbook-stage1 ---
[INFO] Creating staging directory in: C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging
[INFO] Running appcfg --enable_quickstart --disable_update_check -A notused stage C:\Users\Owner\Documents\code\git\google\stage1\target/guestbook-stage1-1.0-SNAPSHOT C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging
Reading application configuration data...

Beginning interaction for module default...
Success.
Temporary staging for module default directory left in C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging
[INFO] Running gcloud app deploy...
[INFO] Running python.exe -S C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py --quiet preview app deploy C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging/app.yaml C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging/index.yaml
[INFO] Traceback (most recent call last):
[INFO]   File "C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py", line 80, in <module>
[INFO]     _DoStartupChecks()
[INFO]   File "C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py", line 72, in _DoStartupChecks
[INFO]     from googlecloudsdk.core.util import platforms
[INFO] ImportError: No module named googlecloudsdk.core.util
[ERROR] Error: gcloud app command with exit code : 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.984 s
[INFO] Finished at: 2015-10-29T23:24:50-04:00
[INFO] Final Memory: 16M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.81.v20151008:deploy (default-cli) on project guestbook-stage1: Error: gcloud app command exit code is: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**What is the output of 'gcloud info'?**
Google Cloud SDK [0.9.84]

Platform: [Windows, x86_64]
Python Version: [2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]]
Site Packages: [Disabled]

Installation Root: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk]
Installed Components:
  core: [2015.10.23]
  app-engine-python: [1.9.27]
  bq-win: [2.0.18]
  core-win: [2015.10.16]
  app: [2015.10.23]
  gcloud: [2015.10.23]
  windows-ssh-tools: [2015.09.21]
  beta: [2015.10.08]
  gsutil: [4.15]
  bq: [2.0.18]
  app-engine-java: [1.9.27]
  gsutil-win: [4.15]
System PATH: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\..\bin\sdk;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Java\jdk1.7.0_79\bin;C:\Program Files\apache-maven-3.3.3\bin;C:\Program Files (x86)\Skype\Phone\;C:\Python27;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;;]
Cloud SDK on PATH: [True]

Installation Properties: [C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\properties]
User Config Directory: [C:\Users\Owner\AppData\Roaming\gcloud]
User Properties: [C:\Users\Owner\AppData\Roaming\gcloud\properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]

Account: [xxxxx@gmail.com]
Project: [xxxxx]

Current Properties:
  [core]
    project: [xxxxx]
    account: [xxxx@gmail.com]
    disable_usage_reporting: [False]
  [app]
    use_appengine_api: [True]
  [compute]
    region: [us-central1]
    zone: [us-central1-f]

Logs Directory: [C:\Users\Owner\AppData\Roaming\gcloud\logs]
Last Log File: [C:\Users\Owner\AppData\Roaming\gcloud\logs\2015.10.31\02.49.48.427000.log]

**Please provide any additional information below**.
I using windows 7, maven 3.3.3
I've followed the exact steps describe in the tutorial. (I've read the tutorial multiple times)
I have to add that the command "mvn gcloud:run" works perfectly, only after I have updated the java component for appengine using the command "gcloud components update app-engine-java". But for some reason the command "mvn gcloud:deploy" has always  given me the same error.

Any help will be extremely appreciated, I've been trying to solve this for days

**Comment by ludoch** [comment]
It seems you are using version :2.0.9.81.v20151008 of the maven plugin.
Can you move to 2.0.9.84.v20151031?

**Comment by coldistric** [comment]
I've move it but I am getting the same error

**output**
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building guestbook-stage1 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> gcloud-maven-plugin:2.0.9.84.v20151031:deploy (default-cli) > package @ guestbook-stage1 >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ guestbook-stage1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Owner\Documents\code\git\google\stage1\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ guestbook-stage1 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ guestbook-stage1 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\Owner\Documents\code\git\google\stage1\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ guestbook-stage1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ guestbook-stage1 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ guestbook-stage1 ---
[INFO] Packaging webapp
[INFO] Assembling webapp [guestbook-stage1] in [C:\Users\Owner\Documents\code\git\google\stage1\target\guestbook-stage1-1.0-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\Users\Owner\Documents\code\git\google\stage1\src\main\webapp]
[INFO] Webapp assembled in [113 msecs]
[INFO] Building war: C:\Users\Owner\Documents\code\git\google\stage1\target\guestbook-stage1-1.0-SNAPSHOT.war
[INFO] WEB-INF\web.xml already added, skipping
[INFO] 
[INFO] <<< gcloud-maven-plugin:2.0.9.84.v20151031:deploy (default-cli) < package @ guestbook-stage1 <<<
[INFO] 
[INFO] --- gcloud-maven-plugin:2.0.9.84.v20151031:deploy (default-cli) @ guestbook-stage1 ---
[INFO] Creating staging directory in: C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging
[INFO] Running appcfg --enable_quickstart --disable_update_check -A notused stage C:\Users\Owner\Documents\code\git\google\stage1\target/guestbook-stage1-1.0-SNAPSHOT C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging
Reading application configuration data...


Beginning interaction for module default...
Success.
Temporary staging for module default directory left in C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging
[INFO] Running gcloud app deploy...
[INFO] Running python.exe -S C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py --quiet preview app deploy C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging/app.yaml C:\Users\Owner\Documents\code\git\google\stage1\target\appengine-staging/index.yaml
[INFO] Traceback (most recent call last):
[INFO]   File "C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py", line 80, in <module>
[INFO]     _DoStartupChecks()
[INFO]   File "C:/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py", line 72, in _DoStartupChecks
[INFO]     from googlecloudsdk.core.util import platforms
[INFO] ImportError: No module named googlecloudsdk.core.util
[ERROR] Error: gcloud app command with exit code : 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.745 s
[INFO] Finished at: 2015-11-04T22:41:41-05:00
[INFO] Final Memory: 16M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.84.v20151031:deploy (default-cli) on project guestbook-stage1: Error: gcloud app command exit code is: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
