### ISSUE TITLE
Vm:true servlet annotations do not map to root

### ISSUE THREAD

**Issue by shun-fan** [GoogleCloudPlatform/gcloud-maven-plugin#68]
I am using App Engine Managed VMs (vm:true) and appengine-web.xml
If I put @WebServlet(name = "root", value = "") and try to map a servlet to root url, I will get a null pointer exception
$ mvn clean gcloud:run

Dec 02, 2015 2:22:00 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml
SEVERE: Received exception processing /Users/sfan/devrel/samples/cloud/getting-started-java/2-structured-data/target/appengine-staging//WEB-INF/min-quickstart-web.xml
java.lang.NullPointerException

The fix right now is to use a web.xml and map servlet to <url-pattern>/</url-pattern>

**Comment by ludoch** [comment]
Please add more info... A zip of the project would help.
For exemple, do you have an entry for quickstart in appengine-web.xml?
Did it work before?

**Comment by ludoch** [comment]
is it:
SEVERE: Received exception processing /Users/ludo/appengine-java-vm-guestbook-extras/stage1/target/appengine-staging//WEB-INF/min-quickstart-web.xml
java.lang.NullPointerException
	at com.google.apphosting.utils.config.YamlUtils.validateUrl(YamlUtils.java:53)
	at com.google.apphosting.utils.config.WebXml.addServletPattern(WebXml.java:59)
	at com.google.apphosting.utils.config.WebXmlReader$1.newNode(WebXmlReader.java:181)
	at com.google.apphosting.utils.config.AbstractConfigXmlReader.parse(AbstractConfigXmlReader.java:206)
	at com.google.apphosting.utils.config.AbstractConfigXmlReader.parse(AbstractConfigXmlReader.java:210)
	at com.google.apphosting.utils.config.AbstractConfigXmlReader.parse(AbstractConfigXmlReader.java:210)
	at com.google.apphosting.utils.config.AbstractConfigXmlReader.parse(AbstractConfigXmlReader.java:193)
	at com.google.apphosting.utils.config.WebXmlReader.processXml(WebXmlReader.java:160)

?

**Comment by ludoch** [comment]
I guess "" is the same semantic as "/" ?

**Comment by shun-fan** [comment]
Yes, that's the same error that I got.
